package main

import (
	"awesomeProject/examples"
)

func main() {
	// When ready to run the commented examples just uncomment them, execute them and comment them back
	// as some of them causes everything to stop
	examples.HelloWorld()
	examples.Values()
	examples.Variables()
	examples.Constants()
	examples.For()
	examples.IfElse()
	examples.Switch()
	examples.Arrays()
	examples.Slices()
	examples.Maps()
	examples.Ranges()
	examples.Functions()
	examples.MultipleReturnValues()
	examples.VariadicFunctions()
	examples.Closures()
	examples.Recursion()
	examples.Pointers()
	examples.Structs()
	examples.Methods()
	examples.Interfaces()
	examples.Errors()
	examples.GoRoutines()
	examples.Channels()
	examples.ChannelBuffering()
	examples.ChannelSincronization()
	examples.ChannelDirections()
	examples.Select()
	examples.TimeOuts() //
	examples.NonBlockingChannels()
	examples.ClosingChannels()
	examples.RangeOverChannels()
	examples.Timers()
	examples.Tickers()
	examples.WorkerPools()
	examples.RateLimiting() // Need to practice this
	examples.AtomicCounters()
	examples.Mutexes()
	examples.StatefulGoRoutines()
	examples.Sorting()
	examples.SortingByFunctions()
	//examples.Panic()
	examples.Defer()
	examples.CollectionFunctions()
	examples.StringFunctions()
	examples.StringFormatting()
	examples.RegularExpressions()
	examples.Json()
	examples.Time()
	examples.Epoch()
	examples.TimeFormattingNParsing()
	examples.RandomNumbers()
	examples.NumberParsing()
	examples.URLParsing()
	examples.Sha1Hashes()
	examples.Base64Encoding()
	examples.ReadingFiles()
	examples.WritingFiles()
	examples.LineFilters()
	examples.CommandLineArguments()
	examples.CommandLineFlags()
	examples.EnvironmentVariables()
	examples.SpawningProcesses()
	//examples.ExecingProcesses()
	//examples.Signals()
	examples.Exit()
	// All Examples.
	// Things of interests goroutines, channels, syncronization, etc
	// This will be published as a public repository
}
