package main

import (
	"awesomeProject/examples"
)

func main() {
	examples.HelloWorld()
	examples.Values()
	examples.Variables()
	examples.Constants()
	examples.For()
	examples.IfElse()
	examples.Switch()
	examples.Arrays()
	examples.Slices()
	examples.Maps()
	examples.Ranges()
	examples.Functions()
	examples.MultipleReturnValues()
	examples.VariadicFunctions()
	examples.Closures()
	examples.Recursion()
	examples.Pointers()
	examples.Structs()
	examples.Methods()
	examples.Interfaces()
	examples.Errors()
	examples.GoRoutines()
	examples.Channels()
	examples.ChannelBuffering()
	examples.ChannelSincronization()
	examples.ChannelDirections()
	examples.Select()
	examples.TimeOuts()
	examples.NonBlockingChannels()
	examples.ClosingChannels()
	examples.RangeOverChannels()
	examples.Timers()
	examples.Tickers()
	examples.WorkerPools()
	examples.RateLimiting()
	examples.AtomicCounters()
	examples.Mutexes()
}
